name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    name: Set up Environment
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Load .env variables
        run: |
          # Load the .env file
          cp app/.env .env

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Python and Node.js dependencies
        run: |
          # Install Python dependencies
          cd app
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          # Install Node.js dependencies
          cd frontend
          npm install
          cd ../..

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: localhost  # This must be 'localhost' as it's internal to the GitHub Actions container
      DB_PORT: ${{ secrets.DB_PORT }}
      DATABASE_URL: postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Load .env variables
        run: |
          # Load the .env file
          cp app/.env .env

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          # Install Python dependencies
          cd app
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          cd app
          python manage.py migrate
          python manage.py test

      - name: Run Frontend Development Server
        run: |
          cd app/frontend
          npm run dev
          cd ../..

  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Backend Docker image
        run: |
          docker build -t app/backend -f app/Dockerfile .

      - name: Build the Frontend Docker image
        run: |
          docker build -t app/frontend -f app/frontend/Dockerfile .
